[project]
name = "RESMA"
version = "0.0.0"
description = "Range Signal Meta Amplifier"
authors = [
    {name = "Christian Camacho", email = "chris.ca.dev@gmail.com"},
]
dependencies = []
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
