#!/bin/bash -e
set -e

if [[ -z "$VERSION_TYPE" ]]; then
  echo "VERSION_TYPE not set. Please set it to one of: patch, minor, major, custom-string"
  exit 1
fi
if [[ "$VERSION_TYPE" -eq "local" && -z "$VERSION_TAG" ]]; then
  echo "VERSION_TAG not set. Please set it to one (eg. gamma, zeta, ubuntu, windows)"
  exit 1
fi

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
"$SCRIPT_DIR/increase-version.sh" $VERSION_TYPE $VERSION_TAG

git add pyproject.toml
