#!/bin/bash -e
set -e

if [[ -z "$VERSION_TYPE" ]]; then
  echo "VERSION_TYPE not set. Please set it to one of: patch, minor, major, custom-string"
  exit 1
fi

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
"$SCRIPT_DIR/increase-version.sh" "$VERSION_TYPE"

git add pyproject.toml
